[build-system]
requires = ["setuptools>=69", "wheel", "cmake>=3.20"]
build-backend = "setuptools.build_meta"

[project]
name = "sirius"
authors = [
  {name = "Amirsadra Mohseni", email = "amohs002@ucr.edu"},
]
version = "1.0.0"
requires-python = ">=3.10"

[project.scripts]
sirius = "sirius.sirius_wrapper:main"

[tool.setuptools.packages.find]
include = ["sirius*"]

[tool.setuptools.package-data]
"sirius" = ["build/sirius", "resources/py27_env.tar.gz"]
"sirius.GeneDiversifier" = ["*.py", "data/*.csv"]
