name: Build and Upload Wheels

on: workflow_dispatch

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build Python wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          # Install EPEL, clean cache, and then install patchelf
          # CIBW_BEFORE_ALL_LINUX: "yum install -y epel-release; yum clean all; yum install -y patchelf"
          CIBW_ENVIRONMENT: 'CXXFLAGS="-march=x86-64 -mtune=generic" CFLAGS="-march=x86-64 -mtune=generic"'
          
          # 2. Ensure these new CXXFLAGS/CFLAGS are passed into the build process
          CIBW_ENVIRONMENT_PASS_LINUX: "CMAKE_BUILD_PARALLEL_LEVEL CXXFLAGS CFLAGS"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2014"

      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: ./wheelhouse/